FROM python:3.7 as builder

WORKDIR /rmazaweb

ENV STATIC_ROOT /rmazaweb/static

COPY . .

RUN pip install -r ./requirements/production.txt
RUN python manage.py collectstatic --no-input


FROM nginx:alpine

WORKDIR /var/www

COPY ./django-nginx-site /etc/nginx/conf.d/default.conf
COPY --from=builder /rmazaweb/static /var/www/static

EXPOSE 80
EXPOSE 443
