version: '3'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        networks:
            - webnet
    web:
        image: rmazaweb
        ports:
            - "80:80"
        environment:
            SECRET_KEY: 213dojf112do213''3][f[3wdc
        depends_on:
            - db
        networks:
            - webnet
networks:
  webnet:
