version: "3.2"

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.app
        env_file: .env

    web:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.web
        volumes:
            - media_data:/var/www/media
        ports:
            - "80:80"
            - "443:443"
        env_file: .env

    db:
        restart: always
        image: postgres:alpine
        volumes:
            - db_data:/var/lib/postgresql/data
#            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        expose:
            - "5432"
        env_file: .env

    redis:
        restart: always
        image: redis:alpine
        expose:
            - "6379"

volumes:
    db_data:
    media_data:
