version: "3"

services:
    app:
        restart: always
        build: .
        env_file: .env

    web:
        restart: always
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        env_file: .env
        volumes:
            - ./static/:/code/static/
            - ./media/:/code/media/
            - ./nginx:/etc/nginx

    db:
        restart: always
        image: postgres:alpine
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        env_file: .env
        expose:
            - "5432"

    redis:
        restart: always
        image: redis:alpine
        expose:
            - "6379"

volumes:
    db_data:
