web:
    restart: always
    build: .
    expose:
        - "8000"
    ports:
        - "8000:8000"
    links:
        - postgres:postgres
        - redis:redis
    env_file: .env
    volumes:
        - .:/code/
    command: /usr/bin/gunicorn rmazaweb.wsgi:application -w 2 -b :8000

nginx:
    restart: always
    image: nginx:alpine
    ports:
        - "80:80"
    volumes_from:
        - web
    volumes:
        - ./nginx:/etc/nginx
    links:
        - web:web

postgres:
    restart: always
    image: postgres
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    expose:
        - "5432"

redis:
    restart: always
    image: redis
    expose:
        - "6379"
