version: "3"

services:
    web:
        restart: always
        build: .
        expose:
            - "8000"
        ports:
            - "8000:8000"
        links:
            - postgres:postgres
            - redis:redis
        env_file: .env
        volumes:
            - .:/code/
        depends_on:
            - "postgres"
        command: sh -c "python3 manage.py migrate && /usr/bin/gunicorn rmazaweb.wsgi:application -w 2 -b :8000"

    nginx:
        restart: always
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/code/
            - ./nginx:/etc/nginx
        links:
            - web:web
        depends_on:
            - "web"

    postgres:
        restart: always
        image: postgres:alpine
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        env_file: .env
        expose:
            - "5432"
        depends_on:
            - "redis"

    redis:
        restart: always
        image: redis:alpine
        expose:
            - "6379"

volumes:
    db_data:
