# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171111_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpageproduct',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='catalogpageproduct',
            name='long_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogpageproduct',
            name='short_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
