# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171111_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpageproduct',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
