# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsettings',
            name='default_per_pages',
            field=models.IntegerField(default=50),
        ),
    ]
