# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20171112_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogsettings',
            old_name='default_per_pages',
            new_name='default_per_page',
        ),
    ]
