# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=255, verbose_name='Company Name')),
                ('company_cif', models.TextField(max_length=255, verbose_name='Company CIF')),
                ('company_location', models.TextField(max_length=255, verbose_name='Location')),
                ('company_phones', wagtail.wagtailcore.fields.RichTextField()),
                ('company_opening_hours', wagtail.wagtailcore.fields.RichTextField()),
                ('company_facebook_url', models.URLField(max_length=255, verbose_name='Facebook URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
