# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
